version = 0.1

[default.build.parameters]
debug = false
use_container = false

[default.deploy.parameters]
debug = false
stack_name = "ai-cloud-engineer"
resolve_s3 = true
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
parameter_overrides = [
  "BedrockRegion=us-west-2",
  "GenerateTemplateModelId=anthropic.claude-3-opus-20240229-v1:0",
  "ReviewTemplateModelId=anthropic.claude-3-haiku-20240307-v1:0",
  "GenerateParamsheetModelId=anthropic.claude-3-haiku-20240307-v1:0"
]
